/* Generated By:JavaCC: Do not edit this line. SILParserConstants.java */
package simpleParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SILParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TRUE = 5;
  /** RegularExpression Id. */
  int FALSE = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int VAR = 9;
  /** RegularExpression Id. */
  int LETTER = 10;
  /** RegularExpression Id. */
  int SIGN = 11;
  /** RegularExpression Id. */
  int SEMICOLON = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int THEN = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int EQUAL = 17;
  /** RegularExpression Id. */
  int AND = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"tt\"",
    "\"ff\"",
    "<NUM>",
    "<DIGIT>",
    "<VAR>",
    "<LETTER>",
    "<SIGN>",
    "\";\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"==\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\"skip\"",
    "\":=\"",
    "\"do\"",
  };

}
